### ISSUE TITLE
Outpainting on M1 not working (AttributeError: module 'scipy' has no attribute 'signal')

### ISSUE THREAD

**Issue by Gitterman69** [FahimF/sd-gui#16]
```
Last login: Mon Oct  3 18:43:52 on ttys000
(base) ➜  ~ conda activate ml
(ml) ➜  ~ cd sd-gui
(ml) ➜  sd-gui git:(main) ✗ python app.py
Init mode: edge_pad
Traceback (most recent call last):
  File "/Users/bamboozle/sd-gui/ui/editor_tab.py", line 366, in do_outpaint
    iarr, marr = self.edge_pad(iarr, marr)
  File "/Users/bamboozle/sd-gui/ui/editor_tab.py", line 544, in edge_pad
    res = scipy.signal.convolve2d(
AttributeError: module 'scipy' has no attribute 'signal'

```

**Comment by FahimF** [comment]
I fixed that last night before I went to bed. If you pull from my repo again, you should have the fixed code.
