### ISSUE TITLE
ModuleNotFoundError: No module named 'darkdetect'

### ISSUE THREAD

**Issue by MartinTale** [FahimF/sd-gui#18]
Getting error below

```
(ml) C:\Users\me\StableDiffusion\sd-gui>python app.py
Traceback (most recent call last):
  File "C:\Users\me\StableDiffusion\sd-gui\app.py", line 11, in <module>
    from ui.generator_tab import GeneratorTab
  File "C:\Users\me\StableDiffusion\sd-gui\ui\generator_tab.py", line 11, in <module>
    from ui.expander import Expander
  File "C:\Users\me\StableDiffusion\sd-gui\ui\expander.py", line 1, in <module>
    import darkdetect
ModuleNotFoundError: No module named 'darkdetect'
```

**Comment by FahimF** [comment]
You would need to install the darkdetect package, which was added today to fix a reported bug, by running pip install from terminal like this:

`pip install darkdetect`

If that doesn't solve the issue, please let me know.

**Comment by MartinTale** [comment]
That fixes it ;) Thanks :)
