### ISSUE TITLE
M1 Mac Pro Monterey macOS // Can't get to run... "No module named 'torch'

### ISSUE THREAD

**Issue by Gitterman69** [FahimF/sd-gui#8]
```
(ml) ➜  sd-gui git:(main) python app.py                                
Traceback (most recent call last):
  File "/Users/bamboozle/sd-gui/app.py", line 5, in <module>
    from tools.config import Config
  File "/Users/bamboozle/sd-gui/tools/config.py", line 7, in <module>
    from tools.sd_engine import GeneratorType
  File "/Users/bamboozle/sd-gui/tools/sd_engine.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

```

**Comment by Gitterman69** [comment]
Fixed this error by reinstalling PyTorch
