### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by Gitterman69** [FahimF/sd-gui#9]
```
(base) ➜  sd-gui git:(main) ✗ conda activate ml
(ml) ➜  sd-gui git:(main) ✗ pip install --upgrade --pre torch==1.13.0.dev20220924 --extra-index-url https://download.pytorch.org/whl/nightly/cpu
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Collecting torch==1.13.0.dev20220924
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev20220924-cp39-none-macosx_11_0_arm64.whl (54.7 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.13.0.dev20220924 typing-extensions-4.3.0
(ml) ➜  sd-gui git:(main) ✗ python app.py
Traceback (most recent call last):
  File "/Users/bamboozle/sd-gui/app.py", line 5, in <module>
    from tools.config import Config
  File "/Users/bamboozle/sd-gui/tools/config.py", line 7, in <module>
    from tools.sd_engine import GeneratorType
  File "/Users/bamboozle/sd-gui/tools/sd_engine.py", line 2, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionInpaintPipeline, StableDiffusionImg2ImgPipeline
ModuleNotFoundError: No module named 'diffusers'
(ml) ➜  sd-gui git:(main) ✗ 

```

**Comment by Gitterman69** [comment]
pip install diffusers....
